### PR TITLE
Replace the google_containers namespace use BASE_IMAGE_NAMESPACE variable

### PR DESCRIPTION
**Pull request by xiaoluhong**
@yasker Replace the google_containers namespace use ADDONS_IMAGE_NAMESPACE variable.

### CODE REVIEW

**Comment by xiaoluhong** [comment]
issue：https://github.com/rancher/rancher/issues/9853

**Comment by yasker** [comment]
LGTM. @alena1108 Can you take a quick look as well?

**Comment by yasker** [comment]
Catalog PR at: https://github.com/rancher/rancher-catalog/pull/867

**Comment by alena1108** [comment]
@yasker Looks good, but we have to decide on the params names (I've made a comment to the corresponding catalog PR). Basically whatever is configured in rancher catalog, should be reflected in this PR

**Comment by xiaoluhong** [comment]
@alena1108  hi ，I updated this variable. Can you check it? Thank you！

**Comment by yasker** [comment]
@hongxiaolu 7 commits? Please squash them into one.

**Comment by alena1108** [comment]
LGTM. @yasker can be merged after it is squashed (and rebased, there are conflicts)

**Comment by yasker** [comment]
LGTM. Remember to put issue URL in the commit message next time.

**Comment by xiaoluhong** [comment]
Thanks very much！

**Pull request merged**
